"""
Enumerations for asset types, relationship types, and other constants.
"""

from enum import Enum


class AssetType(str, Enum):
    """AWS resource types supported for collection."""

    # Compute
    ECS_CLUSTER = "ecs_cluster"
    ECS_SERVICE = "ecs_service"
    ECS_TASK_DEFINITION = "ecs_task_definition"
    EC2_INSTANCE = "ec2_instance"
    LAMBDA_FUNCTION = "lambda_function"

    # Storage
    S3_BUCKET = "s3_bucket"
    EFS_FILESYSTEM = "efs_filesystem"
    EBS_VOLUME = "ebs_volume"

    # Database
    RDS_INSTANCE = "rds_instance"
    RDS_CLUSTER = "rds_cluster"
    ELASTICACHE_CLUSTER = "elasticache_cluster"
    ELASTICACHE_REPLICATION_GROUP = "elasticache_replication_group"
    DYNAMODB_TABLE = "dynamodb_table"

    # Networking
    VPC = "vpc"
    SUBNET = "subnet"
    SECURITY_GROUP = "security_group"
    NETWORK_ACL = "network_acl"
    ROUTE_TABLE = "route_table"
    INTERNET_GATEWAY = "internet_gateway"
    NAT_GATEWAY = "nat_gateway"
    VPC_ENDPOINT = "vpc_endpoint"

    # Load Balancing
    LOAD_BALANCER = "load_balancer"  # ALB/NLB/CLB
    TARGET_GROUP = "target_group"

    # CDN / Edge
    CLOUDFRONT_DISTRIBUTION = "cloudfront_distribution"

    # Security
    WAF_WEB_ACL = "waf_web_acl"
    WAF_RULE_GROUP = "waf_rule_group"
    IAM_ROLE = "iam_role"
    IAM_POLICY = "iam_policy"
    IAM_USER = "iam_user"
    IAM_GROUP = "iam_group"
    KMS_KEY = "kms_key"
    SECRETS_MANAGER_SECRET = "secrets_manager_secret"

    # Messaging
    SQS_QUEUE = "sqs_queue"
    SNS_TOPIC = "sns_topic"

    # Monitoring & Logging
    CLOUDWATCH_ALARM = "cloudwatch_alarm"
    CLOUDWATCH_LOG_GROUP = "cloudwatch_log_group"

    # Other
    UNKNOWN = "unknown"


class RelationshipType(str, Enum):
    """Types of relationships between assets."""

    # Infrastructure relationships
    RUNS_ON = "RUNS_ON"  # ECS Service runs on ECS Cluster
    USES = "USES"  # Service uses Database
    CONNECTED_TO = "CONNECTED_TO"  # Generic connection
    PROTECTED_BY = "PROTECTED_BY"  # Resource protected by Security Group
    ROUTES_TO = "ROUTES_TO"  # Traffic routing
    EXPOSES = "EXPOSES"  # Service exposes via Load Balancer

    # Storage relationships
    STORES_IN = "STORES_IN"  # Data stored in S3/EFS
    BACKS_UP_TO = "BACKS_UP_TO"  # Backup location
    ENCRYPTS_WITH = "ENCRYPTS_WITH"  # KMS key usage

    # Messaging relationships
    PUBLISHES_TO = "PUBLISHES_TO"  # Publishes to SNS/SQS
    SUBSCRIBES_TO = "SUBSCRIBES_TO"  # Subscribes to SNS/SQS
    TRIGGERS = "TRIGGERS"  # Event triggers

    # Security relationships
    ASSUMES_ROLE = "ASSUMES_ROLE"  # IAM role assumption
    HAS_POLICY = "HAS_POLICY"  # Policy attachment
    HAS_PERMISSION = "HAS_PERMISSION"  # Permission grant
    LOGS_TO = "LOGS_TO"  # Logging destination

    # Network relationships
    IN_VPC = "IN_VPC"  # Resource in VPC
    IN_SUBNET = "IN_SUBNET"  # Resource in Subnet
    ALLOWS_TRAFFIC = "ALLOWS_TRAFFIC"  # Security group allows traffic

    # CDN relationships
    ORIGINS_FROM = "ORIGINS_FROM"  # CloudFront origin

    # Monitoring relationships
    MONITORS = "MONITORS"  # Alarm monitors resource
    ALERTS_TO = "ALERTS_TO"  # Alert destination

    # Enrichment relationships
    HAS_ENRICHMENT = "HAS_ENRICHMENT"  # Asset has enrichment data
    OWNED_BY_TEAM = "OWNED_BY_TEAM"  # Business ownership
    SUPPORTS_APPLICATION = "SUPPORTS_APPLICATION"  # Application support
    DEPENDS_ON_EXTERNAL = "DEPENDS_ON_EXTERNAL"  # External dependency


class EnrichmentStatus(str, Enum):
    """Status of enrichment data."""

    ACTIVE = "active"  # Currently active enrichment
    PENDING = "pending"  # Awaiting review/approval
    ARCHIVED = "archived"  # Historical/superseded
    DRAFT = "draft"  # Work in progress


class EnrichmentMethod(str, Enum):
    """Method used to create enrichment."""

    MANUAL = "manual"  # Manually entered by user
    RULE_BASED = "rule_based"  # Applied by automation rule
    LLM = "llm"  # Generated by LLM
    CSV_IMPORT = "csv_import"  # Imported from CSV
    PROPAGATION = "propagation"  # Propagated from related asset
    API_IMPORT = "api_import"  # Imported from external API


class DataClassification(str, Enum):
    """Data sensitivity classification levels."""

    PUBLIC = "public"
    INTERNAL = "internal"
    CONFIDENTIAL = "confidential"
    PII = "pii"  # Personally Identifiable Information
    FINANCIAL = "financial"
    RESTRICTED = "restricted"


class Criticality(str, Enum):
    """Asset criticality tiers."""

    TIER_0 = "tier-0"  # Critical - customer-facing production
    TIER_1 = "tier-1"  # High - production systems
    TIER_2 = "tier-2"  # Medium - staging/important non-prod
    TIER_3 = "tier-3"  # Low - development/test
    TIER_4 = "tier-4"  # Minimal - sandbox/experimental


class Environment(str, Enum):
    """Environment classifications."""

    PRODUCTION = "production"
    STAGING = "staging"
    DEVELOPMENT = "development"
    TEST = "test"
    SANDBOX = "sandbox"
    DR = "disaster-recovery"


class ComplianceFramework(str, Enum):
    """Compliance frameworks."""

    NIST_CSF = "nist-csf"
    PCI_DSS = "pci-dss"
    SOX = "sox"
    GDPR = "gdpr"
    CCPA = "ccpa"
    ISO_27001 = "iso-27001"
    SOC2 = "soc2"
    HIPAA = "hipaa"


# AWS Config resource type mappings to our internal AssetType
AWS_CONFIG_TYPE_MAPPING = {
    "AWS::ECS::Cluster": AssetType.ECS_CLUSTER,
    "AWS::ECS::Service": AssetType.ECS_SERVICE,
    "AWS::ECS::TaskDefinition": AssetType.ECS_TASK_DEFINITION,
    "AWS::EC2::Instance": AssetType.EC2_INSTANCE,
    "AWS::Lambda::Function": AssetType.LAMBDA_FUNCTION,
    "AWS::S3::Bucket": AssetType.S3_BUCKET,
    "AWS::EFS::FileSystem": AssetType.EFS_FILESYSTEM,
    "AWS::EC2::Volume": AssetType.EBS_VOLUME,
    "AWS::RDS::DBInstance": AssetType.RDS_INSTANCE,
    "AWS::RDS::DBCluster": AssetType.RDS_CLUSTER,
    "AWS::ElastiCache::CacheCluster": AssetType.ELASTICACHE_CLUSTER,
    "AWS::ElastiCache::ReplicationGroup": AssetType.ELASTICACHE_REPLICATION_GROUP,
    "AWS::DynamoDB::Table": AssetType.DYNAMODB_TABLE,
    "AWS::EC2::VPC": AssetType.VPC,
    "AWS::EC2::Subnet": AssetType.SUBNET,
    "AWS::EC2::SecurityGroup": AssetType.SECURITY_GROUP,
    "AWS::EC2::NetworkAcl": AssetType.NETWORK_ACL,
    "AWS::EC2::RouteTable": AssetType.ROUTE_TABLE,
    "AWS::EC2::InternetGateway": AssetType.INTERNET_GATEWAY,
    "AWS::EC2::NatGateway": AssetType.NAT_GATEWAY,
    "AWS::EC2::VPCEndpoint": AssetType.VPC_ENDPOINT,
    "AWS::ElasticLoadBalancingV2::LoadBalancer": AssetType.LOAD_BALANCER,
    "AWS::ElasticLoadBalancing::LoadBalancer": AssetType.LOAD_BALANCER,
    "AWS::ElasticLoadBalancingV2::TargetGroup": AssetType.TARGET_GROUP,
    "AWS::CloudFront::Distribution": AssetType.CLOUDFRONT_DISTRIBUTION,
    "AWS::WAFv2::WebACL": AssetType.WAF_WEB_ACL,
    "AWS::WAFv2::RuleGroup": AssetType.WAF_RULE_GROUP,
    "AWS::IAM::Role": AssetType.IAM_ROLE,
    "AWS::IAM::Policy": AssetType.IAM_POLICY,
    "AWS::IAM::User": AssetType.IAM_USER,
    "AWS::IAM::Group": AssetType.IAM_GROUP,
    "AWS::KMS::Key": AssetType.KMS_KEY,
    "AWS::SecretsManager::Secret": AssetType.SECRETS_MANAGER_SECRET,
    "AWS::SQS::Queue": AssetType.SQS_QUEUE,
    "AWS::SNS::Topic": AssetType.SNS_TOPIC,
    "AWS::CloudWatch::Alarm": AssetType.CLOUDWATCH_ALARM,
    "AWS::Logs::LogGroup": AssetType.CLOUDWATCH_LOG_GROUP,
}
